### ISSUE TITLE
Target is always the same

### ISSUE THREAD

**Issue by nsiatras** [pooler/JMiner#3]
Hello

I recently noticed that the sTarget variable in method

Worker.Work(HttpURLConnection conn, URL mainUrl, String auth) throws IOException)

has always the same value:
0000000000000000000000000000000000000000000000000000ffff00000000

Is that correct ?

**Comment by pooler** [comment]
That looks like a difficulty-1 target, which is the historic default for Bitcoin pools. If you connect to a Litecoin pool, you should get a different target.

**Comment by nsiatras** [comment]
Hello

My pool has difficulty 15. What should be the correct one ?

I read that most pools define their target value (minimum value required to earn a "share"), as: 0x00000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffff

Using Java if I multiply the "0x00000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffff" with 15 I get "0x0000000efffffffffffffffffffffffffffffffffffffffffffffffffffffff1"

Is that the correct way to find the target ?
Thank you

**Comment by pooler** [comment]
No, it isn't.
Anyway, it's the server's duty to provide a target, and you have to use whatever the server gives you, so what are you trying to achieve here?

**Comment by nsiatras** [comment]
I am currently using a Stratum proxy for this miner.
I am trying to convert this miner to use the stratum protocol but I have no clue about how to generate the Target Value ... :(

**Comment by nsiatras** [comment]
Any ides will be helpful :)

**Comment by pooler** [comment]
Adding Stratum support is not straightforward. All the information you need is available online at various places (the Bitcoin Wiki, bitcointalk.org, etc.). I'm sorry but right now I'm way too busy with more important projects to help you with this, especially given that nowadays there is very little interest in this miner.

**Comment by nsiatras** [comment]
Thank you for your replies.

I hope to find out the target construction. The thing I have in mind is to make this miner work in cluster using Java MPI but I am stacked with the mining algorithm....

By the way your hasher class is super fast :)
